name: Build and test the fapp/sentry_example ACAP

on:
  push:
    paths:
      - "fapp/sentry_example/**"
      - ".github/workflows/build_fapp_sentry_example.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["armv7hf", "aarch64"]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install FApp CLI and login
        uses: fixedit-ai/install-fappcli-action@main
        with:
          token: ${{ secrets.FAPP_TOKEN }}

      - name: Build ACAP application
        uses: fixedit-ai/build-eap-action@main
        with:
          arch: ${{ matrix.arch }}
          dir: fapp/sentry_example
          fapp-manifest: fapp/sentry_example/fapp-manifest.json

      - name: Validate the content of the ACAP .eap file
        uses: fixedit-ai/test-eap-action@main
        with:
          arch: ${{ matrix.arch }}
          app-path: "fapp/sentry_example/*.eap"
