name: Build and test the hello world ACAP

on:
  push:
    paths:
      - "hello_world/**"
      - ".github/workflows/hello_world.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["armv7hf", "aarch64"]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install FApp CLI and login
        uses: fixedit-ai/install-fappcli-action@main
        with:
          token: ${{ secrets.FAPP_TOKEN }}

      - name: Build ACAP application
        uses: fixedit-ai/build-eap-action@main
        with:
          arch: ${{ matrix.arch }}
          dir: hello_world/

      - name: Validate the content of the ACAP .eap file
        uses: fixedit-ai/test-eap-action@main
        with:
          arch: ${{ matrix.arch }}
          app-path: "hello_world/*.eap"
